CREATE SEQUENCE IF NOT EXISTS revinfo_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE exercise
(
    is_enabled BOOLEAN                                  NOT NULL,
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    name       VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_exercise PRIMARY KEY (id)
);

CREATE TABLE exercise_musclegroup
(
    exercise_id    INTEGER NOT NULL,
    musclegroup_id INTEGER NOT NULL,
    is_enabled     BOOLEAN NOT NULL,
    CONSTRAINT pk_exercise_musclegroup PRIMARY KEY (exercise_id, musclegroup_id)
);

CREATE TABLE muscle_group
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_muscle_group PRIMARY KEY (id)
);

CREATE TABLE revchanges
(
    rev        BIGINT NOT NULL,
    entityname VARCHAR(255)
);

CREATE TABLE revinfo
(
    rev      BIGINT NOT NULL,
    revtstmp BIGINT,
    CONSTRAINT pk_revinfo PRIMARY KEY (rev)
);

CREATE TABLE role_
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50)                              NOT NULL,
    CONSTRAINT pk_role_ PRIMARY KEY (id)
);

CREATE TABLE user_
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    username   VARCHAR(255)                             NOT NULL,
    password   VARCHAR(255)                             NOT NULL,
    role_id    INTEGER,
    CONSTRAINT pk_user_ PRIMARY KEY (id)
);

CREATE TABLE workout_session
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255)                             NOT NULL,
    date    date,
    notes   VARCHAR(255)                             NOT NULL,
    user_id INTEGER                                  NOT NULL,
    CONSTRAINT pk_workout_session PRIMARY KEY (id)
);

CREATE TABLE workout_set
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    weight      DOUBLE PRECISION                         NOT NULL,
    reps        INTEGER                                  NOT NULL,
    order_index INTEGER                                  NOT NULL,
    session_id  INTEGER                                  NOT NULL,
    exercise_id INTEGER                                  NOT NULL,
    CONSTRAINT pk_workout_set PRIMARY KEY (id)
);

ALTER TABLE role_
    ADD CONSTRAINT uc_role__name UNIQUE (name);

ALTER TABLE user_
    ADD CONSTRAINT FK_USER__ON_ROLE FOREIGN KEY (role_id) REFERENCES role_ (id);

ALTER TABLE workout_session
    ADD CONSTRAINT FK_WORKOUT_SESSION_ON_USER FOREIGN KEY (user_id) REFERENCES user_ (id);

ALTER TABLE workout_set
    ADD CONSTRAINT FK_WORKOUT_SET_ON_EXERCISE FOREIGN KEY (exercise_id) REFERENCES exercise (id);

ALTER TABLE workout_set
    ADD CONSTRAINT FK_WORKOUT_SET_ON_SESSION FOREIGN KEY (session_id) REFERENCES workout_session (id);

ALTER TABLE exercise_musclegroup
    ADD CONSTRAINT fk_exemus_on_exercise_entity FOREIGN KEY (exercise_id) REFERENCES exercise (id);

ALTER TABLE exercise_musclegroup
    ADD CONSTRAINT fk_exemus_on_muscle_group_entity FOREIGN KEY (musclegroup_id) REFERENCES muscle_group (id);

ALTER TABLE revchanges
    ADD CONSTRAINT fk_revchanges_on_default_tracking_modified_entities_changelog FOREIGN KEY (rev) REFERENCES revinfo (rev);